version: '2'
services:
  homebridge:
    container_name: homebridge
    image: oznu/homebridge:${HOMEBRIDGE_DOCKER_TAG}
    network_mode: host
    restart: always
    volumes:
      - "${HOMEBRIDGE_VOL}:/homebridge"
    environment:
      - PUID=${HOMEBRIDGE_PUID}
      - PGID=${HOMEBRIDGE_PGID}
      - TZ=${HOMEBRIDGE_TZ}
      - HOMEBRIDGE_CONFIG_UI=${HOMEBRIDGE_CONFIG_UI}
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
