name: "Build"

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Environment
      run: sudo ./.ci/setup.sh

    - name: Build Package
      run: sudo ./.ci/build.sh

    - name: Deploy
      run: sudo ./.ci/deploy.sh
